name: oneway
version: 1.0.0+1
publish_to: none
description: One application for all tasks.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage:
  flutter_local_notifications:
  flutter_native_timezone:
  sizer: ^2.0.15
  http: ^0.13.3
  google_fonts: ^3.0.1
  flutter_spinkit: ^5.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/svg/